Feat/#50 카카오, 네이버 소셜 로그인 구현
danpatime/backend pull request #52
Opened 2024-12-28 04:03 UTC by taeyeongKims

2025-01-04 07:24 UTC, huhdy32 requested changes
application-test.properties 수정 바랍니다 :)

2025-01-06 08:05 UTC, taeyeongKims commented
> application-test.properties 수정 바랍니다 :)

추가 완료했습니다. 

로컬에서 테스트 성공 후 push 했습니다.

2025-01-12 10:36 UTC, huhdy32 approved these changes

2025-01-12 14:10 UTC, yuna83 approved these changes

2025-01-13 00:53 UTC, merged